// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface AmenitiesStoryblok {
  title: string;
  features: FeatureStoryblok[];
  component: "amenities";
  _uid: string;
  [k: string]: any;
}

export interface BannerStoryblok {
  features: FeatureStoryblok[];
  component: "banner";
  _uid: string;
  [k: string]: any;
}

export interface ConfigStoryblok {
  sections: (HeaderStoryblok | FooterStoryblok | PricePerNightStoryblok)[];
  component: "config";
  _uid: string;
  [k: string]: any;
}

export interface ContentAndFormStoryblok {
  content: (
    | DescriptionStoryblok
    | FeaturesStoryblok
    | AmenitiesStoryblok
    | GalleryStoryblok
    | RoomTourStoryblok
    | LocationStoryblok
    | NeighborhoodStoryblok
    | BannerStoryblok
  )[];
  component: "content-and-form";
  _uid: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface DescriptionStoryblok {
  title: string;
  content: RichtextStoryblok;
  component: "description";
  _uid: string;
  [k: string]: any;
}

export interface FeatureStoryblok {
  label?: string;
  title?: string;
  description?: string;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface FeaturesStoryblok {
  title: string;
  features: FeatureStoryblok[];
  component: "features";
  _uid: string;
  [k: string]: any;
}

export interface FloorStoryblok {
  title: string;
  rooms: FeatureStoryblok[];
  component: "floor";
  _uid: string;
  [k: string]: any;
}

export interface FooterStoryblok {
  copyright: string;
  links: LinkStoryblok[];
  component: "footer";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}[];

export interface GalleryStoryblok {
  title: string;
  images: MultiassetStoryblok;
  component: "gallery";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}

export interface HeaderStoryblok {
  headline: string;
  subheadline: string;
  image: AssetStoryblok;
  component: "header";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      anchor?: string;
      rel?: string;
      title?: string;
      prep?: string;
      linktype: "story";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "url";
      rel?: string;
      title?: string;
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      email?: string;
      linktype: "email";
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "asset";
      [k: string]: any;
    };

export interface LinkStoryblok {
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "link";
  _uid: string;
  [k: string]: any;
}

export interface LocationStoryblok {
  title: string;
  address: string;
  image: AssetStoryblok;
  component: "location";
  _uid: string;
  [k: string]: any;
}

export interface NeighborhoodStoryblok {
  title: string;
  description: string;
  features: FeatureStoryblok[];
  images: MultiassetStoryblok;
  component: "neighborhood";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  content: (
    | AmenitiesStoryblok
    | BannerStoryblok
    | ConfigStoryblok
    | ContentAndFormStoryblok
    | DescriptionStoryblok
    | FeatureStoryblok
    | FeaturesStoryblok
    | FloorStoryblok
    | FooterStoryblok
    | GalleryStoryblok
    | HeaderStoryblok
    | LinkStoryblok
    | LocationStoryblok
    | NeighborhoodStoryblok
    | PageStoryblok
    | PricePerNightStoryblok
    | RoomTourStoryblok
  )[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface PricePerNightStoryblok {
  price: string;
  component: "price-per-night";
  _uid: string;
  [k: string]: any;
}

export interface RoomTourStoryblok {
  title: string;
  floors: FloorStoryblok[];
  image: AssetStoryblok;
  component: "room-tour";
  _uid: string;
  [k: string]: any;
}
